version: '3.0'
services:   
    currency-django: 
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
        env_file:
            - ./docker/.env
        volumes:
            - ./:/currency_django
        ports:
            - 8000:8000
        container_name: currency-django
        expose:
            - 8000